- name: Copiar Trino Server para o host
  ansible.builtin.copy:
    src: "trino-server-{{ trino_version }}.tar.gz"
    dest: "/tmp/trino.tar.gz"
    mode: '0644'
    owner: "{{ trino_user }}"
    group: "{{ trino_group }}"

- name: Extrair Trino Server
  ansible.builtin.unarchive:
    src: "/tmp/trino.tar.gz"
    dest: "{{ trino_install_dir }}"
    extra_opts: [--strip-components=1]
    remote_src: yes
    owner: "{{ trino_user }}"
    group: "{{ trino_group }}"
    creates: "{{ trino_install_dir }}/bin/launcher"
